### PR TITLE
Inverted colors

### PR DESCRIPTION
**Pull request by gabe-burnette**
Adds the option for inverted colors, if color is enabled
-n, --invert_color    Inverts the color values

### CODE REVIEW

**Comment by seatedro** [comment]
i'm merging it. fuck the tests

**Comment by kzndotsh** [comment]
> i'm merging it. fuck the tests

real as fuck

**Comment by zyairelai** [comment]
Real Alpha Dig Bick energy 💪🏻

**Comment by JohnAntonios** [comment]
Based

**Comment by devporter007** [comment]
hell yeah

**Pull request merged**
